[build]
  base = "client"
  publish = "client/dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "client"

[[redirects]]
  from = "/api/*"
  to = "https://cybercafe-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhooks/*"
  to = "https://cybercafe-backend.onrender.com/webhooks/:splat"
  status = 200
  force = true

# Optional: fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
